# Generated by Django 6.0.1 on 2026-01-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True)),
                ('responsanvel_financeiro', models.CharField(help_text='Nome do responsável financeiro', max_length=255)),
                ('cpf_responsavel', models.CharField(help_text='Formato: 000.000.000-00', max_length=14)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('data_vencimento_padrao', models.PositiveSmallIntegerField(default=10)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
